# Generated by Django 3.1.7 on 2021-03-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testd', '0002_staffsessions_inout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsessions',
            name='inout',
            field=models.CharField(default=0, max_length=255, verbose_name='Вход/Выход'),
        ),
    ]
