# Generated by Django 3.1.7 on 2021-03-03 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testd', '0003_auto_20210302_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsessions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
