# Generated by Django 3.1.7 on 2021-03-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testd', '0004_staffsessions_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специлизаций')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='lastname',
            field=models.CharField(default='LastName', max_length=255, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=1, upload_to='ProfilePhotos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsessions',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='testd.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='spesilization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testd.spesilization'),
        ),
    ]
